name: Deploy to Juno

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Node はキャッシュ指定なしで入れる
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # pnpm を入れる（このアクションが自動で依存キャッシュを張ります）
      - uses: pnpm/action-setup@v2
        with:
          version: 8          # プロジェクトに合わせて
          run_install: false  # install は後で明示的に

      # 依存インストール
      - run: pnpm install --frozen-lockfile

      # （ビルドが必要なら）- run: pnpm run build

      # デプロイ
      - uses: junobuild/juno-action@main
        with:
          args: deploy
        env:
          JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}
        working-directory: ./my-qr
