jobs:
  publish:
    steps:
      - uses: actions/checkout@v4
        with:
          path: src

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: src/my-qr

      - name: Deploy to Juno
        run: npx juno deploy
        working-directory: src/my-qr
        env:
          JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}
