name: Deploy to Juno

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # ローカルの pnpm のバージョンに合わせて
          run_install: false # install を明示的に別ステップで実行する場合

      - name: Enable Corepack (optional but recommended)
        run: corepack enable

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Deploy to Juno
        uses: junobuild/juno-action@main
        with:
          args: deploy
        env:
          JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}
